# Generated by Django 4.2.4 on 2023-09-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissionsdata', '0002_alter_emissionsdata_emission_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionsdata',
            name='emission_value',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='vehicleemissions',
            name='emission_value',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
