# Generated by Django 4.2.4 on 2023-09-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissionsdata', '0004_alter_emissionsdata_emission_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleemissions',
            name='emission_value',
        ),
        migrations.AddField(
            model_name='vehicleemissions',
            name='emission_values',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='emissionsdata',
            name='emission_value',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
