# Generated by Django 4.2.4 on 2023-09-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissionsdata', '0005_remove_vehicleemissions_emission_value_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleEmissions',
        ),
    ]
