# Generated by Django 4.2.5 on 2023-09-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-09-21T08:31:49.508380Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='limit',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-09-21T08:31:49.508380Z'),
            preserve_default=False,
        ),
    ]
