# Generated by Django 4.2.5 on 2023-09-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limit', '0002_limit_created_at_limit_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
