# Generated by Django 3.2.12 on 2023-09-28 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('emissionsdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionsdata',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_emissionsdata', to='vehicles.vehicle'),
        ),
    ]
