# Generated by Django 3.2.12 on 2023-09-28 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('emissionsdata', '0002_alter_emissionsdata_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionsdata',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
    ]
