# Generated by Django 4.2.1 on 2023-09-21 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_created",
            field=models.DateTimeField(
                null=True,
                verbose_name=datetime.datetime(
                    2023, 9, 21, 19, 51, 33, 933253, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
