# Generated by Django 4.2.4 on 2023-09-22 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 9, 22, 19, 18, 35, 13225, tzinfo=datetime.timezone.utc)),
        ),
    ]
