# Generated by Django 4.2.1 on 2023-09-22 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_confirm_password_alter_user_date_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="confirm_password",
        ),
        migrations.AlterField(
            model_name="user",
            name="date_created",
            field=models.DateTimeField(
                null=True,
                verbose_name=datetime.datetime(
                    2023, 9, 22, 10, 39, 2, 166393, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
