# Generated by Django 4.2.1 on 2023-09-22 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_user_confirm_password_alter_user_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_created",
            field=models.DateTimeField(
                null=True,
                verbose_name=datetime.datetime(
                    2023, 9, 22, 11, 25, 24, 213284, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
