# Generated by Django 4.2.1 on 2023-09-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("limits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="limit",
            name="duration",
            field=models.PositiveIntegerField(),
        ),
    ]
