# Generated by Django 4.2.4 on 2023-09-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissionsdata', '0001_initial'),
        ('limits', '0001_initial'),
      
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_earned', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('emission_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emissionsdata.emissionsdata')),
                ('emission_limit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='limits.limit')),
            ],
        ),
    ]
