# Generated by Django 4.2.5 on 2023-09-25 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("limits", "0001_initial"),
        ("carbon_credits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carboncredits",
            name="emission_limit",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="limits.limit",
            ),
        ),
    ]
