# Generated by Django 3.2.12 on 2023-09-28 08:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20230928_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='home_image',
            field=models.ImageField(default='', upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 9, 28, 8, 13, 18, 662614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 9, 28, 8, 13, 18, 662637, tzinfo=utc)),
        ),
    ]
