# Generated by Django 3.2.12 on 2023-09-28 08:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20230928_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 9, 28, 8, 18, 41, 973236, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2023, 9, 28, 8, 18, 41, 973267, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_image',
            field=models.ImageField(null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='user_images/'),
        ),
    ]
