
# name: Backend CI/CD Pipelineon:
#   push:
#     branches:
#       - main
#       - staging
#       - dev
#   pull_request:
#     branches:
#       - main
#       - staging
#       - dev
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Set Python version
#         run: echo "Using Python version 3.9"
#       - name: Install requirements
#         run: pip install -r requirements.txt
#       - name: Check Syntax
#         run: pre-commit run --all-files
#       - name: Make Migrations
#         run: python manage.py makemigrations
#       - name: Migration
#         run: |
#           python3 manage.py migrate
#       - name: Run server
#         run: |
#           python3 manage.py runserver
#       - name: Run Tests
#         run: |
#           python manage.py test
